### PR TITLE
user/signup endpoint - controller, service, dao, Rest E H

### PR DESCRIPTION
**Pull request by Chirag-debug**
Made changes to following, kindly review and merge the pull request:
1) UserController - signup method
2) UserBusinessService - completed signup method
3) UserDao - completed createUser method, getUserByUserName method, getUserByEmail method
4) RestExceptionHandler - completed signuprestricted method

Note: Ignore pull request for:
1)  .idea/Quora_Assignment.iml
2) .idea/vcs.xml

### CODE REVIEW

**Review by ChethanShetty563 — CHANGES_REQUESTED** [review]
Chirag,
Whatever steps you have followed is good.
But there is one issue over here.
In Service class you have used nested loop, assume if i give the different username with existed email id.
Expected behavior : It should through the exception
But in your case it will signup successfully
Make the changes and submit

**Comment by Chirag-debug** [comment]
Lets discuss to understand more

**Comment by Chirag-debug** [comment]
Well... whenever the exception is thrown data will not persist hence no user will be created. Data only persists when all conditions are met. No issue in Nesting at all. 

Still to try your test case, I gave different username with existing email id, following is the output. I think its good to go.

{
  "code": "SGR-002",
  "message": "This user has already been registered, try with any other emailId",
  "root_cause": null
}

**Comment by ChethanShetty563** [comment]
Well its correct while tracing i have done the mistake. Merging your changes

**Pull request merged**
